services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    depends_on:
      - server
    ports: 
      - 3000:3000
    restart: always
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile 
    ports: 
      - 8000:8000
    restart: always
